ALTER TABLE public.authority
    OWNER TO postgres;
ALTER TABLE public.authority_id_seq
    OWNER TO postgres;
ALTER TABLE public.authority_seq
    OWNER TO postgres;
ALTER TABLE public.auto_tag_instructions
    OWNER TO postgres;
ALTER TABLE public.auto_tag_instructions_sequence
    OWNER TO postgres;
ALTER TABLE public.calculated_stats
    OWNER TO postgres;
ALTER TABLE public.category_relation
    OWNER TO postgres;
ALTER TABLE public.category_relation_sequence
    OWNER TO postgres;
ALTER TABLE public.category_tags
    OWNER TO postgres;
ALTER TABLE public.dish
    OWNER TO postgres;
ALTER TABLE public.dish_sequence
    OWNER TO postgres;
ALTER TABLE public.dish_tags
    OWNER TO postgres;

ALTER TABLE public.hibernate_sequence
    OWNER TO postgres;
ALTER TABLE public.list
    OWNER TO postgres;
ALTER TABLE public.list_category
    OWNER TO postgres;
ALTER TABLE public.list_item
    OWNER TO postgres;
ALTER TABLE public.list_item_sequence
    OWNER TO postgres;
ALTER TABLE public.list_layout
    OWNER TO postgres;
ALTER TABLE public.list_layout_category_sequence
    OWNER TO postgres;
ALTER TABLE public.list_layout_sequence
    OWNER TO postgres;
ALTER TABLE public.list_sequence
    OWNER TO postgres;
ALTER TABLE public.list_stat_configs
    OWNER TO postgres;
ALTER TABLE public.list_tag_stats
    OWNER TO postgres;
ALTER TABLE public.list_tag_stats_sequence
    OWNER TO postgres;
ALTER TABLE public.meal_plan
    OWNER TO postgres;
ALTER TABLE public.meal_plan_sequence
    OWNER TO postgres;
ALTER TABLE public.meal_plan_slot
    OWNER TO postgres;
ALTER TABLE public.meal_plan_slot_sequence
    OWNER TO postgres;
ALTER TABLE public.proposal
    OWNER TO postgres;
ALTER TABLE public.proposal_approach
    OWNER TO postgres;
ALTER TABLE public.proposal_approach_sequence
    OWNER TO postgres;
ALTER TABLE public.proposal_context
    OWNER TO postgres;
ALTER TABLE public.proposal_context_sequence
    OWNER TO postgres;
ALTER TABLE public.proposal_context_slot_sequence
    OWNER TO postgres;
ALTER TABLE public.proposal_dish
    OWNER TO postgres;
ALTER TABLE public.proposal_dish_sequence
    OWNER TO postgres;
ALTER TABLE public.proposal_sequence
    OWNER TO postgres;
ALTER TABLE public.proposal_slot
    OWNER TO postgres;
ALTER TABLE public.proposal_slot_sequence
    OWNER TO postgres;
ALTER TABLE public.shadow_tags
    OWNER TO postgres;
ALTER TABLE public.shadow_tags_sequence
    OWNER TO postgres;
ALTER TABLE public.tag
    OWNER TO postgres;
ALTER TABLE public.tag_extended
    OWNER TO postgres;
ALTER TABLE public.tag_relation
    OWNER TO postgres;
ALTER TABLE public.tag_relation_sequence
    OWNER TO postgres;
ALTER TABLE public.tag_search_group
    OWNER TO postgres;
ALTER TABLE public.tag_search_group_sequence
    OWNER TO postgres;
ALTER TABLE public.tag_sequence
    OWNER TO postgres;
ALTER TABLE public.target
    OWNER TO postgres;
ALTER TABLE public.target_proposal_dish_sequence
    OWNER TO postgres;
ALTER TABLE public.target_proposal_sequence
    OWNER TO postgres;
ALTER TABLE public.target_proposal_slot_sequence
    OWNER TO postgres;
ALTER TABLE public.target_sequence
    OWNER TO postgres;
ALTER TABLE public.target_slot
    OWNER TO postgres;
ALTER TABLE public.target_slot_sequence
    OWNER TO postgres;
ALTER TABLE public.user_device_sequence
    OWNER TO postgres;
ALTER TABLE public.user_devices
    OWNER TO postgres;
ALTER TABLE public.user_id_sequence
    OWNER TO postgres;
ALTER TABLE public.users
    OWNER TO postgres;
