delete from modifier_mappings where mapping_id > 0;

insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (100, 'Unit', '#2 cans', '#2 can');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (150, 'Unit', '#2 can', '#2 can');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (200, 'Unit', '#2.5 cans', '#2.5 can');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (250, 'Unit', '#2.5 can', '#2.5 can');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (300, 'Unit', '#3 cans', '#3 can');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (350, 'Unit', '#3 can', '#3 can');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (400, 'Unit', '14.5 oz cans', '14.5 oz can');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (450, 'Unit', '14.5 oz can', '14.5 oz can');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (500, 'Unit', '29 oz cans', '29 oz can');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (550, 'Unit', '29 oz can', '29 oz can');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (600, 'Unit', 'bulbs', 'bulb');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (650, 'Unit', 'bulb', 'bulb');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (700, 'Unit', 'cans', 'can');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (750, 'Unit', 'can', 'can');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (800, 'Unit', 'centiliters', 'centiliter');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (850, 'Unit', 'centiliter', 'centiliter');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (900, 'Unit', 'cl', 'centiliter');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (950, 'Unit', 'cl.', 'centiliter');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1000, 'Unit', 'cups', 'cup');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1050, 'Unit', 'cup', 'cup');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1100, 'Unit', 'C', 'cup');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1150, 'Unit', 'C.', 'cup');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1200, 'Unit', 'c', 'cup');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1250, 'Unit', 'c.', 'cup');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1300, 'Unit', 'fluid cups', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1350, 'Unit', 'cups', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1400, 'Unit', 'fluid cup', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1450, 'Unit', 'cup', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1500, 'Unit', 'fl. cups', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1550, 'Unit', 'fl. cup', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1600, 'Unit', 'fl. c.', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1650, 'Unit', 'fl. c', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1700, 'Unit', 'fl.cup', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1750, 'Unit', 'fl.cups', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1800, 'Unit', 'C', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1850, 'Unit', 'C.', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1900, 'Unit', 'c', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (1950, 'Unit', 'c.', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2000, 'Unit', 'fl. C.', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2050, 'Unit', 'fl C', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2100, 'Unit', 'fl. C', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2150, 'Unit', 'fl. c ', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2200, 'Unit', 'fl. c. ', 'cup (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2250, 'Unit', 'cups', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2300, 'Unit', 'cup', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2350, 'Unit', 'fluid cups', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2400, 'Unit', 'fluid cup', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2450, 'Unit', 'fl. cups', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2500, 'Unit', 'fl. cup', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2550, 'Unit', 'fl. c.', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2600, 'Unit', 'fl. c', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2650, 'Unit', 'fl.cup', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2700, 'Unit', 'fl.cups', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2750, 'Unit', 'fl. C.', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2800, 'Unit', 'fl C', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2850, 'Unit', 'fl. C', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2900, 'Unit', 'fl. c ', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (2950, 'Unit', 'fl. c. ', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3000, 'Unit', 'C.', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3050, 'Unit', 'c.', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3100, 'Unit', 'fluid cups (UK )', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3150, 'Unit', 'fluid cup (UK )', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3200, 'Unit', 'fl. cups (UK )', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3250, 'Unit', 'fl. cup (UK )', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3300, 'Unit', 'fl. c. (UK )', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3350, 'Unit', 'fl. c (UK )', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3400, 'Unit', 'fl.cup (UK )', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3450, 'Unit', 'fl.cups (UK )', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3500, 'Unit', 'fl. C. (UK )', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3550, 'Unit', 'fl C (UK )', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3600, 'Unit', 'fl. C (UK )', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3650, 'Unit', 'fl. c  (UK )', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3700, 'Unit', 'fl. c.  (UK )', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3750, 'Unit', 'C', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3800, 'Unit', 'c', 'cup (fluid) (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3850, 'Unit', 'ears', 'ear');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3900, 'Unit', 'ear', 'ear');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (3950, 'Unit', 'fl oz', 'fl oz');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4000, 'Unit', 'fluid ounces', 'fl oz');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4050, 'Unit', 'fluid ounce', 'fl oz');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4100, 'Unit', 'fl ounces', 'fl oz');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4150, 'Unit', 'fl ounce', 'fl oz');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4200, 'Unit', 'fluid oz ', 'fl oz');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4250, 'Unit', 'fluid oz.', 'fl oz');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4300, 'Unit', 'fl oz', 'fl oz (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4350, 'Unit', 'fluid ounces', 'fl oz (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4400, 'Unit', 'fluid ounce', 'fl oz (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4450, 'Unit', 'fl ounces', 'fl oz (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4500, 'Unit', 'fl ounce', 'fl oz (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4550, 'Unit', 'fluid oz ', 'fl oz (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4600, 'Unit', 'fluid oz.', 'fl oz (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4650, 'Unit', 'fl oz', 'fl oz (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4700, 'Unit', 'fl oz (UK)', 'fl oz (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4750, 'Unit', 'fluid ounces (UK)', 'fl oz (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4800, 'Unit', 'fluid ounce (UK)', 'fl oz (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4850, 'Unit', 'fl ounces (UK)', 'fl oz (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4900, 'Unit', 'fl ounce (UK)', 'fl oz (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (4950, 'Unit', 'fluid oz  (UK)', 'fl oz (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5000, 'Unit', 'fluid oz. (UK)', 'fl oz (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5050, 'Unit', 'fl oz (UK)', 'fl oz (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5100, 'Unit', 'gallons', 'gallon');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5150, 'Unit', 'gallon', 'gallon');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5200, 'Unit', 'gal', 'gallon');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5250, 'Unit', 'gal.', 'gallon');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5300, 'Unit', 'Gal.', 'gallon');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5350, 'Unit', 'Gal', 'gallon');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5400, 'Unit', 'gallons', 'gallon (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5450, 'Unit', 'gallon', 'gallon (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5500, 'Unit', 'gal', 'gallon (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5550, 'Unit', 'gal.', 'gallon (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5600, 'Unit', 'Gal.', 'gallon (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5650, 'Unit', 'Gal', 'gallon (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5700, 'Unit', 'grams', 'gram');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5750, 'Unit', 'gram', 'gram');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5800, 'Unit', 'gr.', 'gram');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5850, 'Unit', 'gr', 'gram');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5900, 'Unit', 'heads', 'head');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5950, 'Unit', 'head', 'head');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6000, 'Unit', 'kilograms', 'kilogram');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6050, 'Unit', 'kilogram', 'kilogram');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6100, 'Unit', 'kg', 'kilogram');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6150, 'Unit', 'kg.', 'kilogram');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6200, 'Unit', 'large cans', 'large can');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6250, 'Unit', 'large can', 'large can');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6300, 'Unit', 'lbs.', 'lb');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6350, 'Unit', 'lbs', 'lb');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6400, 'Unit', 'lb.', 'lb');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6450, 'Unit', 'lb', 'lb');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6500, 'Unit', '#', 'lb');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6550, 'Unit', 'pound', 'lb');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6600, 'Unit', 'pounds', 'lb');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6600, 'Unit', 'leaves', 'leaf');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6600, 'Unit', 'leaf', 'leaf');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6650, 'Unit', 'liters', 'liter');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6700, 'Unit', 'liter', 'liter');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6750, 'Unit', 'L', 'liter');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6800, 'Unit', 'L.', 'liter');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6850, 'Unit', 'milliliters', 'milliliter');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6900, 'Unit', 'milliliter', 'milliliter');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (6950, 'Unit', 'ml', 'milliliter');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7000, 'Unit', 'ml.', 'milliliter');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7050, 'Unit', 'ounces', 'ounce');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7100, 'Unit', 'ounce', 'ounce');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7150, 'Unit', 'oz', 'ounce');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7200, 'Unit', 'ozs', 'ounce');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7250, 'Unit', 'oz.', 'ounce');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7300, 'Unit', 'ozs.', 'ounce');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7350, 'Unit', 'packages', 'package');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7400, 'Unit', 'package', 'package');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7450, 'Unit', 'pkg.', 'package');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7500, 'Unit', 'pkg', 'package');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7550, 'Unit', 'pkgs', 'package');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7600, 'Unit', 'pkgs.', 'package');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7650, 'Unit', 'packets', 'packet');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7700, 'Unit', 'packet', 'packet');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7750, 'Unit', 'pints', 'pint');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7800, 'Unit', 'pint', 'pint');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7850, 'Unit', 'pt', 'pint');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7900, 'Unit', 'pt.', 'pint');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (7950, 'Unit', 'PT.', 'pint');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8000, 'Unit', 'PT', 'pint');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8050, 'Unit', 'pint', 'pint (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8100, 'Unit', 'pints', 'pint (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8150, 'Unit', 'pt', 'pint (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8200, 'Unit', 'pt.', 'pint (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8250, 'Unit', 'PT.', 'pint (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8300, 'Unit', 'PT', 'pint (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8350, 'Unit', 'quarts', 'quart');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8400, 'Unit', 'quart', 'quart');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8450, 'Unit', 'qts', 'quart');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8500, 'Unit', 'qts.', 'quart');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8550, 'Unit', 'qt.', 'quart');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8600, 'Unit', 'qt', 'quart');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8650, 'Unit', 'quarts', 'quart (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8700, 'Unit', 'quart', 'quart (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8750, 'Unit', 'qts', 'quart (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8800, 'Unit', 'qts.', 'quart (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8850, 'Unit', 'qt.', 'quart (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8900, 'Unit', 'qt', 'quart (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (8950, 'Unit', 'quarts (UK)', 'quart (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9000, 'Unit', 'quart (UK)', 'quart (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9050, 'Unit', 'qts (UK)', 'quart (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9100, 'Unit', 'qts. (UK)', 'quart (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9150, 'Unit', 'qt. (UK)', 'quart (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9200, 'Unit', 'qt (UK)', 'quart (UK)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9250, 'Unit', 'sl.', 'slice');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9300, 'Unit', 'sl', 'slice');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9350, 'Unit', 'slices', 'slice');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9400, 'Unit', 'slice', 'slice');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9450, 'Unit', 'small cans', 'small can');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9500, 'Unit', 'small can', 'small can');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9550, 'Unit', 'sticks', 'stick');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9600, 'Unit', 'stick', 'stick');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9650, 'Unit', 'st.', 'stick');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9700, 'Unit', 'st', 'stick');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9750, 'Unit', 'tablespoons', 'tablespoon');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9800, 'Unit', 'tablespoon', 'tablespoon');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9850, 'Unit', 'T.', 'tablespoon');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9900, 'Unit', 't.', 'tablespoon');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (9950, 'Unit', 'tablespoons', 'tablespoon (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10000, 'Unit', 'Tb.', 'tablespoon (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10050, 'Unit', 'Tb', 'tablespoon (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10100, 'Unit', 'tbsp.', 'tablespoon (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10150, 'Unit', 'tbsp', 'tablespoon (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10200, 'Unit', 'tablespoon', 'tablespoon (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10250, 'Unit', 'teaspoon', 'teaspoon');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10300, 'Unit', 'teaspoons', 'teaspoon');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10350, 'Unit', 'tsp.', 'teaspoon');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10400, 'Unit', 'tsp', 'teaspoon');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10450, 'Unit', 'teaspoons', 'teaspoon');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10500, 'Unit', 'tsp.', 'teaspoon');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10550, 'Unit', 'tsp', 'teaspoon');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10600, 'Unit', 'fl teaspoon', 'teaspoon (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10650, 'Unit', 'fluid teaspoon', 'teaspoon (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10700, 'Unit', 'teaspoon (fl.)', 'teaspoon (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10750, 'Unit', 'fl tsp', 'teaspoon (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10800, 'Unit', 'fl tsp.', 'teaspoon (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10850, 'Unit', 'fluid tsp.', 'teaspoon (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10900, 'Unit', 'fluid tsp', 'teaspoon (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (10950, 'Unit', 'fluid t', 'teaspoon (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (11000, 'Unit', 'fluid t.', 'teaspoon (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (11050, 'Unit', 'tsp (fl.)', 'teaspoon (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (11100, 'Unit', 'tsp (fluid)', 'teaspoon (fluid)');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (11150, 'Unit', 'pinch', 'pinch');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (11200, 'Unit', 'pinches', 'pinch');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (11250, 'Unit', 'sticks', 'butter stick');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (11300, 'Unit', 'stick', 'butter stick');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (11350, 'Unit', 'jars', 'jar');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (11400, 'Unit', 'jar', 'jar');



insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20000, 'Marker', 'loosely packed', 'firmly packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20050, 'Marker', 'chunked', 'chunked');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20100, 'Marker', 'crumbled', 'crumbled');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20150, 'Marker', 'crushed', 'crushed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20200, 'Marker', 'cubed', 'cubed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20250, 'Marker', 'diced', 'diced');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20300, 'Marker', 'drained', 'drained');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20350, 'Marker', 'firmly packed', 'firmly packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20400, 'Marker', 'frozen', 'frozen');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20450, 'Marker', 'grated', 'grated');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20500, 'Marker', 'halved', 'halved');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20550, 'Marker', 'kernels', 'kernels');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20600, 'Marker', 'loosely packed', 'loosely packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20650, 'Marker', 'mashed', 'mashed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20700, 'Marker', 'melted', 'melted');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20750, 'Marker', 'packed', 'packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20800, 'Marker', 'pared', 'pared');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20850, 'Marker', 'pieces', 'pieces');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20900, 'Marker', 'pitted', 'pitted');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (20950, 'Marker', 'powdered', 'powdered');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21000, 'Marker', 'pulp', 'pulp');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21050, 'Marker', 'pureed', 'pureed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21100, 'Marker', 'quartered', 'quartered');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21150, 'Marker', 'rounded', 'rounded');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21200, 'Marker', 'rounds', 'rounds');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21250, 'Marker', 'sectioned', 'sectioned');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21300, 'Marker', 'shaved', 'shaved');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21350, 'Marker', 'shelled', 'shelled');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21400, 'Marker', 'shredded', 'shredded');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21450, 'Marker', 'sifted', 'sifted');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21500, 'Marker', 'sliced', 'sliced');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21550, 'Marker', 'slivered', 'slivered');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21600, 'Marker', 'solid', 'solid');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21650, 'Marker', 'undrained', 'undrained');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21700, 'Marker', 'unpacked', 'unpacked');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21750, 'Marker', 'unsifted', 'unsifted');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21800, 'Marker', 'unthawed', 'unthawed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21850, 'Marker', 'whole', 'whole');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21900, 'Marker', 'chopped', 'chunked');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (21950, 'Marker', 'chopped', 'cubed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22000, 'Marker', 'chopped', 'diced');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22050, 'Marker', 'chunked', 'chopped');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22100, 'Marker', 'chunked', 'cubed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22150, 'Marker', 'chunked', 'diced');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22200, 'Marker', 'cubed', 'chopped');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22250, 'Marker', 'cubed', 'chunked');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22300, 'Marker', 'cubed', 'diced');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22350, 'Marker', 'diced', 'chopped');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22400, 'Marker', 'diced', 'chunked');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22450, 'Marker', 'diced', 'cubed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22500, 'Marker', 'sliced', 'slivered');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22550, 'Marker', 'slivered', 'sliced');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22600, 'Marker', 'grated', 'shredded');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22650, 'Marker', 'shredded', 'grated');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22700, 'Marker', 'firmly packed', 'loosely packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22750, 'Marker', 'firmly packed', 'packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22800, 'Marker', 'chopped', 'chopped');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22850, 'Marker', 'loosely packed', 'packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22900, 'Marker', 'packed', 'firmly packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (22950, 'Marker', 'packed', 'loosely packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (23000, 'Marker', 'mashed', 'pureed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (23050, 'Marker', 'pureed', 'mashed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (23100, 'Marker', 'wedge', 'wedge');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (23150, 'UnitSize', 'large', 'large');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (23200, 'UnitSize', 'medium', 'medium');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (23250, 'UnitSize', 'small', 'small');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (23300, 'UnitSize', 'extra-large', 'extra large');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (23350, 'UnitSize', 'xl', 'extra large');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (23400, 'UnitSize', 'lg', 'large');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (23450, 'UnitSize', 'lg.', 'large');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (23500, 'UnitSize', 'med.', 'medium');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (23550, 'UnitSize', 'med', 'medium');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (23600, 'UnitSize', 'sm', 'small');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (23650, 'UnitSize', 'sm.', 'small');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (23700, 'UnitSize', 'extra large', 'extra large');



update modifier_mappings m set reference_id = u.unit_id from units u where m.mapped_modifier = u.name and modifier_type = 'Unit';