delete from modifier_mappings where mapping_id > 0;

insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5189, 'Marker', 'chopped', 'chopped', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5190, 'Marker', 'chunked', 'chunked', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5191, 'Marker', 'crumbled', 'crumbled', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5192, 'Marker', 'crushed', 'crushed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5193, 'Marker', 'cubed', 'cubed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5194, 'Marker', 'diced', 'diced', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5195, 'Marker', 'drained', 'drained', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5196, 'Marker', 'firmly packed', 'firmly packed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5197, 'Marker', 'frozen', 'frozen', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5198, 'Marker', 'grated', 'grated', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5199, 'Marker', 'halved', 'halved', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5200, 'Marker', 'kernels', 'kernels', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5201, 'Marker', 'loosely packed', 'loosely packed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5202, 'Marker', 'mashed', 'mashed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5203, 'Marker', 'melted', 'melted', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5204, 'Marker', 'packed', 'packed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5205, 'Marker', 'pared', 'pared', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5206, 'Marker', 'pieces', 'pieces', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5207, 'Marker', 'pitted', 'pitted', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5208, 'Marker', 'powdered', 'powdered', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5209, 'Marker', 'pulp', 'pulp', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5210, 'Marker', 'pureed', 'pureed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5211, 'Marker', 'quartered', 'quartered', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5212, 'Marker', 'rounded', 'rounded', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5213, 'Marker', 'rounds', 'rounds', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5214, 'Marker', 'sectioned', 'sectioned', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5215, 'Marker', 'shaved', 'shaved', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5216, 'Marker', 'shelled', 'shelled', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5217, 'Marker', 'shredded', 'shredded', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5218, 'Marker', 'sifted', 'sifted', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5219, 'Marker', 'sliced', 'sliced', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5220, 'Marker', 'slivered', 'slivered', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5221, 'Marker', 'solid', 'solid', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5222, 'Marker', 'undrained', 'undrained', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5223, 'Marker', 'unpacked', 'unpacked', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5224, 'Marker', 'unsifted', 'unsifted', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5225, 'Marker', 'unthawed', 'unthawed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5227, 'Marker', 'whole', 'whole', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5228, 'Marker', 'chopped', 'chunked', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5229, 'Marker', 'chopped', 'cubed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5230, 'Marker', 'chopped', 'diced', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5231, 'Marker', 'chunked', 'chopped', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5232, 'Marker', 'chunked', 'cubed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5233, 'Marker', 'chunked', 'diced', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5234, 'Marker', 'cubed', 'chopped', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5235, 'Marker', 'cubed', 'chunked', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5236, 'Marker', 'cubed', 'diced', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5237, 'Marker', 'diced', 'chopped', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5238, 'Marker', 'diced', 'chunked', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5239, 'Marker', 'diced', 'cubed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5240, 'Marker', 'sliced', 'slivered', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5241, 'Marker', 'slivered', 'sliced', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5242, 'Marker', 'grated', 'shredded', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5243, 'Marker', 'shredded', 'grated', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5244, 'Marker', 'firmly packed', 'loosely packed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5245, 'Marker', 'firmly packed', 'packed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5246, 'Marker', 'loosely packed', 'firmly packed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5247, 'Marker', 'loosely packed', 'packed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5248, 'Marker', 'packed', 'firmly packed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5249, 'Marker', 'packed', 'loosely packed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5250, 'Marker', 'mashed', 'pureed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5251, 'Marker', 'pureed', 'mashed', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5252, 'UnitSize', 'extra large', 'extra large', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5253, 'UnitSize', 'large', 'large', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5254, 'UnitSize', 'medium', 'medium', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5255, 'UnitSize', 'small', 'small', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5256, 'UnitSize', 'extra-large', 'extra large', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5257, 'UnitSize', 'xl', 'extra large', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5258, 'UnitSize', 'lg', 'large', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5259, 'UnitSize', 'lg.', 'large', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5260, 'UnitSize', 'med.', 'medium', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5261, 'UnitSize', 'med', 'medium', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5262, 'UnitSize', 'sm', 'small', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5263, 'UnitSize', 'sm.', 'small', null);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (5226, 'Marker', 'wedge', 'wedge', 1050);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1600, 'Unit', 'cup', 'cup', 1000);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1601, 'Unit', 'cups', 'cup', 1000);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1602, 'Unit', 'C', 'cup', 1000);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1603, 'Unit', 'c.', 'cup', 1000);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1604, 'Unit', 'C.', 'cup', 1000);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1605, 'Unit', 'C', 'cup', 1000);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1606, 'Unit', 'tablespoon', 'tablespoon', 1001);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1607, 'Unit', 'T.', 'tablespoon', 1001);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1608, 'Unit', 'tablespoons', 'tablespoon', 1001);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1609, 'Unit', 'Tb.', 'tablespoon', 1001);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1610, 'Unit', 'Tb', 'tablespoon', 1001);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1611, 'Unit', 'tbsp.', 'tablespoon', 1001);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1612, 'Unit', 'tbsp', 'tablespoon', 1001);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1613, 'Unit', 'teaspoon', 'teaspoon', 1002);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1614, 'Unit', 'teaspoons', 'teaspoon', 1002);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1615, 'Unit', 't', 'teaspoon', 1002);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1616, 'Unit', 't.', 'teaspoon', 1002);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1617, 'Unit', 'tsp.', 'teaspoon', 1002);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1618, 'Unit', 'tsp', 'teaspoon', 1002);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1619, 'Unit', 'liter', 'liter', 1003);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1620, 'Unit', 'L.', 'liter', 1003);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1621, 'Unit', 'L', 'liter', 1003);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1622, 'Unit', 'l.', 'liter', 1003);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1623, 'Unit', 'l', 'liter', 1003);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1624, 'Unit', 'milliliter', 'milliliter', 1004);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1625, 'Unit', 'ml.', 'milliliter', 1004);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1626, 'Unit', 'ml', 'milliliter', 1004);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1627, 'Unit', 'gallon', 'gallon', 1005);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1628, 'Unit', 'gal.', 'gallon', 1005);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1629, 'Unit', 'gal', 'gallon', 1005);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1630, 'Unit', 'gl', 'gallon', 1005);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1631, 'Unit', 'gl.', 'gallon', 1005);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1632, 'Unit', 'Gal.', 'gallon', 1005);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1633, 'Unit', 'Gal', 'gallon', 1005);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1634, 'Unit', 'GL.', 'gallon', 1005);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1635, 'Unit', 'GL', 'gallon', 1005);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1636, 'Unit', 'pint', 'pint', 1006);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1637, 'Unit', 'pt', 'pint', 1006);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1638, 'Unit', 'pt.', 'pint', 1006);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1639, 'Unit', 'PT.', 'pint', 1006);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1640, 'Unit', 'PT', 'pint', 1006);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1641, 'Unit', 'fl oz', 'fl oz', 1007);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1642, 'Unit', 'fluid ounces', 'fl oz', 1007);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1643, 'Unit', 'lb', 'lb', 1008);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1644, 'Unit', 'pound', 'lb', 1008);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1645, 'Unit', '#', 'lb', 1008);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1646, 'Unit', 'lb.', 'lb', 1008);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1647, 'Unit', 'lbs.', 'lb', 1008);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1648, 'Unit', 'lbs', 'lb', 1008);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1649, 'Unit', 'pounds', 'lb', 1008);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1650, 'Unit', 'oz', 'oz', 1009);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1651, 'Unit', 'ounce', 'oz', 1009);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1652, 'Unit', 'ounces', 'oz', 1009);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1653, 'Unit', 'quart', 'quart', 1010);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1654, 'Unit', 'quarts', 'quart', 1010);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1655, 'Unit', 'qt', 'quart', 1010);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1656, 'Unit', 'qt.', 'quart', 1010);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1657, 'Unit', 'qts', 'quart', 1010);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1658, 'Unit', 'qts.', 'quart', 1010);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1659, 'Unit', 'gram', 'gram', 1013);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1660, 'Unit', 'grams', 'gram', 1013);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1661, 'Unit', 'gr', 'gram', 1013);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1662, 'Unit', 'gr.', 'gram', 1013);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1663, 'Unit', 'kilogram', 'kilogram', 1014);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1664, 'Unit', 'kg', 'kilogram', 1014);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1665, 'Unit', 'kg.', 'kilogram', 1014);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1666, 'Unit', 'kgs.', 'kilogram', 1014);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1667, 'Unit', 'kgs', 'kilogram', 1014);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1668, 'Unit', 'k.', 'kilogram', 1014);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1669, 'Unit', 'k', 'kilogram', 1014);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1670, 'Unit', 'centiliter', 'centiliter', 1015);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1671, 'Unit', 'cl', 'centiliter', 1015);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1672, 'Unit', 'cl.', 'centiliter', 1015);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1673, 'Unit', 'centiliters', 'centiliter', 1015);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1674, 'Unit', 'cup', 'cup (fluid)', 1017);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1675, 'Unit', 'Cups', 'cup (fluid)', 1017);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1676, 'Unit', 'C', 'cup (fluid)', 1017);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1677, 'Unit', 'c.', 'cup (fluid)', 1017);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1678, 'Unit', 'C.', 'cup (fluid)', 1017);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1679, 'Unit', 'C', 'cup (fluid)', 1017);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1680, 'Unit', 'teaspoon', 'teaspoon (fluid)', 1019);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1681, 'Unit', 'teaspoons', 'teaspoon (fluid)', 1019);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1682, 'Unit', 't', 'teaspoon (fluid)', 1019);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1683, 'Unit', 't.', 'teaspoon (fluid)', 1019);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1684, 'Unit', 'tsp.', 'teaspoon (fluid)', 1019);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1685, 'Unit', 'tsp', 'teaspoon (fluid)', 1019);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1686, 'Unit', 'tablespoon', 'tablespoon (fluid)', 1021);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1687, 'Unit', 'T.', 'tablespoon (fluid)', 1021);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1688, 'Unit', 'tablespoons', 'tablespoon (fluid)', 1021);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1689, 'Unit', 'Tb.', 'tablespoon (fluid)', 1021);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1690, 'Unit', 'Tb', 'tablespoon (fluid)', 1021);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1691, 'Unit', 'tbsp.', 'tablespoon (fluid)', 1021);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1692, 'Unit', 'tbsp', 'tablespoon (fluid)', 1021);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1693, 'Unit', 'slice', 'slice', 1022);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1694, 'Unit', 'sl.', 'slice', 1022);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1695, 'Unit', 'sl', 'slice', 1022);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1696, 'Unit', 'slices', 'slice', 1022);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1697, 'Unit', 'stick', 'stick', 1023);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1698, 'Unit', 'sticks', 'stick', 1023);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1699, 'Unit', 'st.', 'stick', 1023);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1700, 'Unit', 'st', 'stick', 1023);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1701, 'Unit', 'gallon', 'gallon (UK)', 1024);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1702, 'Unit', 'gal.', 'gallon (UK)', 1024);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1703, 'Unit', 'gal', 'gallon (UK)', 1024);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1704, 'Unit', 'gl', 'gallon (UK)', 1024);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1705, 'Unit', 'gl.', 'gallon (UK)', 1024);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1706, 'Unit', 'Gal.', 'gallon (UK)', 1024);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1707, 'Unit', 'Gal', 'gallon (UK)', 1024);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1708, 'Unit', 'GL.', 'gallon (UK)', 1024);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1709, 'Unit', 'GL', 'gallon (UK)', 1024);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1710, 'Unit', 'pint', 'pint (UK)', 1025);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1711, 'Unit', 'pt', 'pint (UK)', 1025);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1712, 'Unit', 'pt.', 'pint (UK)', 1025);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1713, 'Unit', 'PT.', 'pint (UK)', 1025);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1714, 'Unit', 'PT', 'pint (UK)', 1025);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1715, 'Unit', 'fl oz', 'fl oz (UK)', 1026);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1716, 'Unit', 'fluid ounces', 'fl oz (UK)', 1026);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1717, 'Unit', 'quart (UK)', 'quart (UK)', 1027);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1718, 'Unit', 'quart', 'quart (UK)', 1027);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1719, 'Unit', 'quarts', 'quart (UK)', 1027);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1720, 'Unit', 'qt', 'quart (UK)', 1027);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1721, 'Unit', 'qt.', 'quart (UK)', 1027);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1722, 'Unit', 'qts', 'quart (UK)', 1027);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1723, 'Unit', 'qts.', 'quart (UK)', 1027);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1724, 'Unit', 'cup (fluid) (UK)', 'cup (fluid) (UK)', 1028);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1725, 'Unit', 'cup', 'cup (fluid) (UK)', 1028);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1726, 'Unit', 'cups', 'cup (fluid) (UK)', 1028);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1727, 'Unit', 'C', 'cup (fluid) (UK)', 1028);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1728, 'Unit', 'c.', 'cup (fluid) (UK)', 1028);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1729, 'Unit', 'C.', 'cup (fluid) (UK)', 1028);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1730, 'Unit', 'C', 'cup (fluid) (UK)', 1028);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1731, 'Unit', 'can', 'can', 1029);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1732, 'Unit', 'cans', 'can', 1029);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1733, 'Unit', 'large can', 'large can', 1030);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1734, 'Unit', 'large cans', 'large can', 1030);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1735, 'Unit', 'small can', 'small can', 1031);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1736, 'Unit', 'small cans', 'small can', 1031);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1737, 'Unit', '#2 can', '#2 can', 1032);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1738, 'Unit', '#2 cans', '#2 can', 1032);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1739, 'Unit', '14.5 oz can', '14.5 oz can', 1033);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1740, 'Unit', '14.5 oz cans', '14.5 oz can', 1033);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1741, 'Unit', '#2.5 can', '#2.5 can', 1034);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1742, 'Unit', '#2.5 cans', '#2.5 can', 1034);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1743, 'Unit', '#3 cans', '#3 can', 1035);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1744, 'Unit', '29 oz can', '29 oz can', 1036);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1745, 'Unit', '29 oz cans', '29 oz can', 1036);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1746, 'Unit', 'bulb', 'bulb', 1037);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1747, 'Unit', 'bulbs', 'bulb', 1037);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1748, 'Unit', 'ears', 'ear', 1038);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1749, 'Unit', 'head', 'head', 1039);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1750, 'Unit', 'leaf', 'leaf', 1040);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1751, 'Unit', 'leaves', 'leaf', 1040);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1752, 'Unit', 'package', 'package', 1041);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1753, 'Unit', 'packages', 'package', 1041);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1754, 'Unit', 'pkg.', 'package', 1041);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1755, 'Unit', 'pkg', 'package', 1041);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1756, 'Unit', 'pkgs', 'package', 1041);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1757, 'Unit', 'pkgs.', 'package', 1041);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1758, 'Unit', 'packet', 'packet', 1042);
insert into public.modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier, reference_id) values (1759, 'Unit', 'Packets', 'packet', 1042);
