delete from modifier_mappings where mapping_id > 0;

insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5189, 'Marker', 'chopped', 'chopped');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5190, 'Marker', 'chunked', 'chunked');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5191, 'Marker', 'crumbled', 'crumbled');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5192, 'Marker', 'crushed', 'crushed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5193, 'Marker', 'cubed', 'cubed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5194, 'Marker', 'diced', 'diced');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5195, 'Marker', 'drained', 'drained');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5196, 'Marker', 'firmly packed', 'firmly packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5197, 'Marker', 'frozen', 'frozen');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5198, 'Marker', 'grated', 'grated');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5199, 'Marker', 'halved', 'halved');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5200, 'Marker', 'kernels', 'kernels');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5201, 'Marker', 'loosely packed', 'loosely packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5202, 'Marker', 'mashed', 'mashed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5203, 'Marker', 'melted', 'melted');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5204, 'Marker', 'packed', 'packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5205, 'Marker', 'pared', 'pared');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5206, 'Marker', 'pieces', 'pieces');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5207, 'Marker', 'pitted', 'pitted');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5208, 'Marker', 'powdered', 'powdered');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5209, 'Marker', 'pulp', 'pulp');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5210, 'Marker', 'pureed', 'pureed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5211, 'Marker', 'quartered', 'quartered');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5212, 'Marker', 'rounded', 'rounded');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5213, 'Marker', 'rounds', 'rounds');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5214, 'Marker', 'sectioned', 'sectioned');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5215, 'Marker', 'shaved', 'shaved');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5216, 'Marker', 'shelled', 'shelled');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5217, 'Marker', 'shredded', 'shredded');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5218, 'Marker', 'sifted', 'sifted');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5219, 'Marker', 'sliced', 'sliced');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5220, 'Marker', 'slivered', 'slivered');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5221, 'Marker', 'solid', 'solid');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5222, 'Marker', 'undrained', 'undrained');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5223, 'Marker', 'unpacked', 'unpacked');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5224, 'Marker', 'unsifted', 'unsifted');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5225, 'Marker', 'unthawed', 'unthawed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5226, 'Marker', 'wedge', 'wedge');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5227, 'Marker', 'whole', 'whole');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5228, 'Marker', 'chopped', 'chunked');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5229, 'Marker', 'chopped', 'cubed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5230, 'Marker', 'chopped', 'diced');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5231, 'Marker', 'chunked', 'chopped');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5232, 'Marker', 'chunked', 'cubed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5233, 'Marker', 'chunked', 'diced');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5234, 'Marker', 'cubed', 'chopped');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5235, 'Marker', 'cubed', 'chunked');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5236, 'Marker', 'cubed', 'diced');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5237, 'Marker', 'diced', 'chopped');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5238, 'Marker', 'diced', 'chunked');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5239, 'Marker', 'diced', 'cubed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5240, 'Marker', 'sliced', 'slivered');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5241, 'Marker', 'slivered', 'sliced');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5242, 'Marker', 'grated', 'shredded');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5243, 'Marker', 'shredded', 'grated');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5244, 'Marker', 'firmly packed', 'loosely packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5245, 'Marker', 'firmly packed', 'packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5246, 'Marker', 'loosely packed', 'firmly packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5247, 'Marker', 'loosely packed', 'packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5248, 'Marker', 'packed', 'firmly packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5249, 'Marker', 'packed', 'loosely packed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5250, 'Marker', 'mashed', 'pureed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5251, 'Marker', 'pureed', 'mashed');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5252, 'UnitSize', 'extra large', 'extra large');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5253, 'UnitSize', 'large', 'large');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5254, 'UnitSize', 'medium', 'medium');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5255, 'UnitSize', 'small', 'small');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5256, 'UnitSize', 'extra-large', 'extra large');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5257, 'UnitSize', 'xl', 'extra large');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5258, 'UnitSize', 'lg', 'large');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5259, 'UnitSize', 'lg.', 'large');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5260, 'UnitSize', 'med.', 'medium');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5261, 'UnitSize', 'med', 'medium');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5262, 'UnitSize', 'sm', 'small');
insert into modifier_mappings (mapping_id, modifier_type, modifier, mapped_modifier) values (5263, 'UnitSize', 'sm.', 'small');
