<!doctype html>
<head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Poppins">
    <style>
        table {
            padding: 20px 30px 20px 20px;
        }

        @media only screen and (max-width: 620px) {
            body {
                min-height: 844px;
            }

            a {
                font-size: large;
            }

            table {
                padding: 20px 20px 20px 20px;
            }
        }
    </style>
</head>

<body style="font-family: Poppins;
    background: linear-gradient(to top left, #dddbe000 6%, #dddbe0 232%);
    background-size: 100% auto;
    background-repeat: no-repeat;
    min-height: 1000px;
font-size: large">
<div></div>
<table style="    margin-top: 40px;
    background-color: white;
    min-width: 500px;
    margin-left: auto;
    margin-right: auto;
    border-radius: 20px;
    border-color: #c2c0c5;
    border-style: solid;
    box-shadow: 10px 10px 26px 5px rgb(0 0 0 / 28%);">
    <tr>
        <td><img style="width:75px;margin-top:-40px; margin-left:40px;" src="${staticRoot}/images/check.png"></td>
    </tr>
    <tr>
        <td>
            <p>Hello!</p>
            <p>Thanks for your interest in testing! </p>
            <p>To install <span style="
    font-weight: bold;
    /*letter-spacing: 1px;*/
    color: #777777;
    text-transform: uppercase;">the list shop
            </span> on your phone, you'll use an application called Test
                Flight. TestFlight is an Apple application which allows you to install apps which are in the test phase,
                and not yet
                available in the app store. So, you'll install TestFlight, and then use TestFlight to install <span
                        style="
    font-weight: bold;
    /*letter-spacing: 1px;*/
    color: #777777;
    text-transform: uppercase;">the list shop
            </span></p>
            <p>To install the test version:</p>
            <ul>
                <li>Install TestFlight from the App Store.</li>
                <li>Get access to the list shop test by clicking on this <a style="text-align: center;
    text-decoration: underline;" href="${testLink}">link</a> from your phone
                </li>
                <li>TestFlight will open automatically, and you'll see information about the application</li>
                <li>Click on Install to install the application</li>
            </ul>

            <p>Now, you're ready to test! You'll use the same username and password which you use on the web page.
                Install it, try it out, and let us know what you think - we're interested in any and all feedback!</p>
            <p>If you have any issues with the installation, please let us know.</p>
            <p>See you soon!</p>
            <div style="vertical-align: top">
                <div style="background-image: url(${staticRoot}/images/smallorangelogo.png);
                        width: 90px;
                        height: 90px;
                        background-repeat: no-repeat;
                        display: inline-block;
                        text-align: justify;
                        vertical-align: center;box-sizing: border-box;"></div>
                <div style="    padding: 5px 10px 10px 10px;
    display: inline-block;
    font-weight: 400;
    line-height: 30px;
    font-size: 20px;
    letter-spacing: 1px;
    color: #e67d21;
    text-transform: uppercase;
    vertical-align: bottom;
    margin-left: -30px;
    margin-bottom: 15px;
    box-sizing: border-box;">the list shop
                </div>

            </div>

        </td>
    </tr>
</table>

</body>
