apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "listshop-api.fullname" . }}-configmap
  namespace: listshop
  labels:
    {{- include "listshop-api.labels" . | nindent 4 }}
data:
  application.properties: |-
    # logging
    metrics.cron.expression=0 0 */3 * * *