apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "listshop-api.fullname" . }}
  namespace: listshop
  labels:
    {{- include "listshop-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "listshop-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "listshop-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: additional-app-configs
          configMap:
            name: {{ include "listshop-api.fullname" . }}-configmap
            items:
              - key: application.properties
                path: application.properties
      serviceAccountName: {{ include "listshop-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LISTSHOP_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.service.secrets }}
                  key: emailPassword
            - name: LISTSHOP_SERVER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.service.secrets }}
                  key: dbPassword
            - name: LISTSHOP_SERVER_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.service.secrets }}
                  key: dbUser
            - name: LISTSHOP_SERVER_DB_URL
              value: {{ .Values.service.database.url }}
            - name: LISTSHOP_SERVER_PORT
              value: '{{ .Values.service.port }}'
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.service.profile }}
            - name: JDK_JAVA_OPTIONS
              value: >-
                -Dspring.config.additional-location=optional:/app/additional-app-configs/application.properties
          volumeMounts:
            - name: additional-app-configs
              mountPath: /app/additional-app-configs
              readOnly: true
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: 4
            periodSeconds: 60
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            failureThreshold: 4
            periodSeconds: 60
            initialDelaySeconds: 60
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
