update tag set conversion_id = null where conversion_id is not null;

delete from factors where factors.factor_id > 0;
delete from units where unit_id > 0;


insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1000, 'cup', 'HYBRID', 'SOLID',FALSE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1001, 'tablespoon', 'HYBRID', 'SOLID',FALSE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1002, 'teaspoon', 'HYBRID', 'SOLID',FALSE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1019, 'teaspoon (fluid)', 'HYBRID', 'LIQUID',FALSE, TRUE,TRUE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1021, 'tablespoon (fluid)', 'HYBRID', 'LIQUID',FALSE, TRUE,TRUE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1022, 'slice', 'HYBRID', 'SOLID',FALSE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1023, 'stick', 'HYBRID', 'SOLID',FALSE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1003, 'liter', 'METRIC', 'VOLUME',TRUE, TRUE,TRUE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1004, 'milliliter', 'METRIC', 'VOLUME',TRUE, TRUE,TRUE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1013, 'gram', 'METRIC', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1014, 'kilogram', 'METRIC', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1015, 'centiliter', 'METRIC', 'VOLUME',FALSE, TRUE,TRUE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1016, 'milligram', 'METRIC', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1005, 'gallon', 'US', 'VOLUME',TRUE, TRUE,TRUE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1006, 'pint', 'US', 'VOLUME',FALSE, TRUE,TRUE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1007, 'fl oz', 'US', 'VOLUME',TRUE, TRUE,TRUE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1008, 'lb', 'US', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1009, 'oz', 'US', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1010, 'quart', 'US', 'VOLUME',TRUE, TRUE,TRUE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1017, 'cup (fluid)', 'US', 'VOLUME',FALSE, TRUE,TRUE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1011, 'unit', 'UNIT', 'NONE',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1024, 'gallon (UK)', 'UK', 'VOLUME',TRUE, TRUE,TRUE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1025, 'pint (UK)', 'UK', 'VOLUME',FALSE, TRUE,TRUE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1026, 'fl oz (UK)', 'UK', 'VOLUME',TRUE, TRUE,TRUE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1027, 'quart (UK)', 'UK', 'VOLUME',TRUE, TRUE,TRUE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1028, 'cup (fluid) (UK)', 'UK', 'VOLUME',FALSE, TRUE,TRUE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1029, 'can', 'HYBRID', 'VOLUME',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1030, 'large can', 'HYBRID', 'VOLUME',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1031, 'small can', 'HYBRID', 'VOLUME',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1032, '#2 can', 'US', 'VOLUME',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1033, '14.5 oz can', 'US', 'VOLUME',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1034, '#2.5 can', 'US', 'VOLUME',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1035, '#3 can', 'US', 'VOLUME',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1036, '29 oz can', 'US', 'VOLUME',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1037, 'bulb', 'HYBRID', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1038, 'ear', 'HYBRID', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1039, 'head', 'HYBRID', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1040, 'leaf', 'HYBRID', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1041, 'package', 'HYBRID', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1042, 'packet', 'HYBRID', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1043, 'pod', 'HYBRID', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1044, 'ring', 'HYBRID', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1045, 'sheet', 'HYBRID', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1046, 'spear', 'HYBRID', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1047, 'sprig', 'HYBRID', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1048, 'stalk', 'HYBRID', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1049, 'stick', 'HYBRID', 'WEIGHT',TRUE, TRUE,FALSE);
insert into units (unit_id, name, type, subtype, is_list_unit, is_dish_unit, is_liquid) values (1050, 'wedge', 'HYBRID', 'WEIGHT',TRUE, TRUE,FALSE);

insert into factors (factor_id, from_unit, to_unit, factor) select 1, f.unit_id, t.unit_id, 0.0625 as factor from units f,units t where lower(f.name) = 'cup (fluid)' and lower(t.name) = 'gallon';
insert into factors (factor_id, from_unit, to_unit, factor) select 2, f.unit_id, t.unit_id, 0.5 as factor from units f,units t where lower(f.name) = 'cup (fluid)' and lower(t.name) = 'pint';
insert into factors (factor_id, from_unit, to_unit, factor) select 3, f.unit_id, t.unit_id, 0.25 as factor from units f,units t where lower(f.name) = 'cup (fluid)' and lower(t.name) = 'quart';
insert into factors (factor_id, from_unit, to_unit, factor) select 4, f.unit_id, t.unit_id, 0.125 as factor from units f,units t where lower(f.name) = 'fl oz' and lower(t.name) = 'cup (fluid)';
insert into factors (factor_id, from_unit, to_unit, factor) select 5, f.unit_id, t.unit_id, 0.0078125 as factor from units f,units t where lower(f.name) = 'fl oz' and lower(t.name) = 'gallon';
insert into factors (factor_id, from_unit, to_unit, factor) select 6, f.unit_id, t.unit_id, 0.0625 as factor from units f,units t where lower(f.name) = 'fl oz' and lower(t.name) = 'pint';
insert into factors (factor_id, from_unit, to_unit, factor) select 7, f.unit_id, t.unit_id, 0.03125 as factor from units f,units t where lower(f.name) = 'fl oz' and lower(t.name) = 'quart';
insert into factors (factor_id, from_unit, to_unit, factor) select 8, f.unit_id, t.unit_id, 0.001 as factor from units f,units t where lower(f.name) = 'gram' and lower(t.name) = 'kilogram';
insert into factors (factor_id, from_unit, to_unit, factor) select 9, f.unit_id, t.unit_id, 0.0022 as factor from units f,units t where lower(f.name) = 'gram' and lower(t.name) = 'lb';
insert into factors (factor_id, from_unit, to_unit, factor) select 10, f.unit_id, t.unit_id, 0.0352733686067019 as factor from units f,units t where lower(f.name) = 'gram' and lower(t.name) = 'oz';
insert into factors (factor_id, from_unit, to_unit, factor) select 11, f.unit_id, t.unit_id, 2.20462262 as factor from units f,units t where lower(f.name) = 'kilogram' and lower(t.name) = 'lb';
insert into factors (factor_id, from_unit, to_unit, factor) select 12, f.unit_id, t.unit_id, 35.2733686067019 as factor from units f,units t where lower(f.name) = 'kilogram' and lower(t.name) = 'oz';
insert into factors (factor_id, from_unit, to_unit, factor) select 13, f.unit_id, t.unit_id, 100 as factor from units f,units t where lower(f.name) = 'liter' and lower(t.name) = 'centiliter';
insert into factors (factor_id, from_unit, to_unit, factor) select 14, f.unit_id, t.unit_id, 4.22675 as factor from units f,units t where lower(f.name) = 'liter' and lower(t.name) = 'cup (fluid)';
insert into factors (factor_id, from_unit, to_unit, factor) select 15, f.unit_id, t.unit_id, 0.26417 as factor from units f,units t where lower(f.name) = 'liter' and lower(t.name) = 'gallon';
insert into factors (factor_id, from_unit, to_unit, factor) select 16, f.unit_id, t.unit_id, 1000 as factor from units f,units t where lower(f.name) = 'liter' and lower(t.name) = 'milliliter';
insert into factors (factor_id, from_unit, to_unit, factor) select 17, f.unit_id, t.unit_id, 2.1133764 as factor from units f,units t where lower(f.name) = 'liter' and lower(t.name) = 'pint';
insert into factors (factor_id, from_unit, to_unit, factor) select 18, f.unit_id, t.unit_id, 1.05668821 as factor from units f,units t where lower(f.name) = 'liter' and lower(t.name) = 'quart';
insert into factors (factor_id, from_unit, to_unit, factor) select 19, f.unit_id, t.unit_id, 0.00422675 as factor from units f,units t where lower(f.name) = 'milliliter' and lower(t.name) = 'cup (fluid)';
insert into factors (factor_id, from_unit, to_unit, factor) select 20, f.unit_id, t.unit_id, 0.00026417 as factor from units f,units t where lower(f.name) = 'milliliter' and lower(t.name) = 'gallon';
insert into factors (factor_id, from_unit, to_unit, factor) select 21, f.unit_id, t.unit_id, 0.0021133764 as factor from units f,units t where lower(f.name) = 'milliliter' and lower(t.name) = 'pint';
insert into factors (factor_id, from_unit, to_unit, factor) select 22, f.unit_id, t.unit_id, 0.0010566882 as factor from units f,units t where lower(f.name) = 'milliliter' and lower(t.name) = 'quart';
insert into factors (factor_id, from_unit, to_unit, factor) select 23, f.unit_id, t.unit_id, 0.125 as factor from units f,units t where lower(f.name) = 'pint' and lower(t.name) = 'gallon';
insert into factors (factor_id, from_unit, to_unit, factor) select 24, f.unit_id, t.unit_id, 0.5 as factor from units f,units t where lower(f.name) = 'pint' and lower(t.name) = 'quart';
insert into factors (factor_id, from_unit, to_unit, factor) select 25, f.unit_id, t.unit_id, 0.25 as factor from units f,units t where lower(f.name) = 'quart' and lower(t.name) = 'gallon';
insert into factors (factor_id, from_unit, to_unit, factor) select 26, f.unit_id, t.unit_id, 0.0000022 as factor from units f,units t where lower(f.name) = 'milligram' and lower(t.name) = 'lb';
insert into factors (factor_id, from_unit, to_unit, factor) select 27, f.unit_id, t.unit_id, 0.00003527 as factor from units f,units t where lower(f.name) = 'milligram' and lower(t.name) = 'oz';
insert into factors (factor_id, from_unit, to_unit, factor) select 28, f.unit_id, t.unit_id, 0.0105668821 as factor from units f,units t where lower(f.name) = 'centiliter' and lower(t.name) = 'quart';
insert into factors (factor_id, from_unit, to_unit, factor) select 29, f.unit_id, t.unit_id, 0.0422675 as factor from units f,units t where lower(f.name) = 'centiliter' and lower(t.name) = 'cup (fluid)';
insert into factors (factor_id, from_unit, to_unit, factor) select 30, f.unit_id, t.unit_id, 0.0026417205124156 as factor from units f,units t where lower(f.name) = 'centiliter' and lower(t.name) = 'gallon';
insert into factors (factor_id, from_unit, to_unit, factor) select 31, f.unit_id, t.unit_id, 0.021133764 as factor from units f,units t where lower(f.name) = 'centiliter' and lower(t.name) = 'pint';
insert into factors (factor_id, from_unit, to_unit, factor) select 32, f.unit_id, t.unit_id, 0.001 as factor from units f,units t where lower(f.name) = 'milliliter' and lower(t.name) = 'liter';
insert into factors (factor_id, from_unit, to_unit, factor) select 33, f.unit_id, t.unit_id, 0.1 as factor from units f,units t where lower(f.name) = 'milliliter' and lower(t.name) = 'centiliter';
insert into factors (factor_id, from_unit, to_unit, factor) select 34, f.unit_id, t.unit_id, 0.01 as factor from units f,units t where lower(f.name) = 'centiliter' and lower(t.name) = 'liter';
insert into factors (factor_id, from_unit, to_unit, factor) select 35, f.unit_id, t.unit_id, 10 as factor from units f,units t where lower(f.name) = 'centiliter' and lower(t.name) = 'milliliter';
insert into factors (factor_id, from_unit, to_unit, factor) select 36, f.unit_id, t.unit_id, 0.0625 as factor from units f,units t where lower(f.name) = 'oz' and lower(t.name) = 'lb';
insert into factors (factor_id, from_unit, to_unit, factor) select 37, f.unit_id, t.unit_id, 16 as factor from units f,units t where lower(f.name) = 'lb' and lower(t.name) = 'oz';
insert into factors (factor_id, from_unit, to_unit, factor) select 38, f.unit_id, t.unit_id, 0.3333333333 as factor from units f,units t where lower(f.name) = 'teaspoon (fluid)' and lower(t.name) = 'tablespoon (fluid)';
insert into factors (factor_id, from_unit, to_unit, factor) select 39, f.unit_id, t.unit_id, 0.33333333333 as factor from units f,units t where lower(f.name) = 'teaspoon' and lower(t.name) = 'tablespoon';
insert into factors (factor_id, from_unit, to_unit, factor) select 40, f.unit_id, t.unit_id, 0.020833333333 as factor from units f,units t where lower(f.name) = 'teaspoon' and lower(t.name) = 'cup';
insert into factors (factor_id, from_unit, to_unit, factor) select 41, f.unit_id, t.unit_id, 0.020833333333 as factor from units f,units t where lower(f.name) = 'teaspoon (fluid)' and lower(t.name) = 'cup (fluid)';
insert into factors (factor_id, from_unit, to_unit, factor) select 42, f.unit_id, t.unit_id, 0.020833333333 as factor from units f,units t where lower(f.name) = 'teaspoon' and lower(t.name) = 'cup';
insert into factors (factor_id, from_unit, to_unit, factor) select 43, f.unit_id, t.unit_id, 0.0625 as factor from units f,units t where lower(f.name) = 'tablespoon' and lower(t.name) = 'cup';
insert into factors (factor_id, from_unit, to_unit, factor) select 44, f.unit_id, t.unit_id, 0.0625 as factor from units f,units t where lower(f.name) = 'tablespoon (fluid)' and lower(t.name) = 'cup (fluid)';
insert into factors (factor_id, from_unit, to_unit, factor) select 45, f.unit_id, t.unit_id, 3.0 as factor from units f,units t where lower(f.name) = 'tablespoon' and lower(t.name) = 'teaspoon';
insert into factors (factor_id, from_unit, to_unit, factor) select 46, f.unit_id, t.unit_id, 3.0 as factor from units f,units t where lower(f.name) = 'tablespoon (fluid)' and lower(t.name) = 'teaspoon (fluid)';
insert into factors (factor_id, from_unit, to_unit, factor) select 47, f.unit_id, t.unit_id, 0.00390625 as factor from units f,units t where lower(f.name) = 'tablespoon (fluid)' and lower(t.name) = 'gallon';
insert into factors (factor_id, from_unit, to_unit, factor) select 48, f.unit_id, t.unit_id, 0.03125 as factor from units f,units t where lower(f.name) = 'tablespoon (fluid)' and lower(t.name) = 'pint';
insert into factors (factor_id, from_unit, to_unit, factor) select 49, f.unit_id, t.unit_id, 0.5 as factor from units f,units t where lower(f.name) = 'tablespoon (fluid)' and lower(t.name) = 'fl oz';
insert into factors (factor_id, from_unit, to_unit, factor) select 50, f.unit_id, t.unit_id, 0.015625 as factor from units f,units t where lower(f.name) = 'tablespoon (fluid)' and lower(t.name) = 'quart';
insert into factors (factor_id, from_unit, to_unit, factor) select 51, f.unit_id, t.unit_id, 0.00130208333 as factor from units f,units t where lower(f.name) = 'teaspoon (fluid)' and lower(t.name) = 'gallon';
insert into factors (factor_id, from_unit, to_unit, factor) select 52, f.unit_id, t.unit_id, 0.0104166666666 as factor from units f,units t where lower(f.name) = 'teaspoon (fluid)' and lower(t.name) = 'pint';
insert into factors (factor_id, from_unit, to_unit, factor) select 53, f.unit_id, t.unit_id, 0.1666666666 as factor from units f,units t where lower(f.name) = 'teaspoon (fluid)' and lower(t.name) = 'fl oz';
insert into factors (factor_id, from_unit, to_unit, factor) select 54, f.unit_id, t.unit_id, 0.00520833333333 as factor from units f,units t where lower(f.name) = 'teaspoon (fluid)' and lower(t.name) = 'quart';
insert into factors (factor_id, from_unit, to_unit, factor) select 55, f.unit_id, t.unit_id, 0.0078125 as factor from units f,units t where lower(f.name) = 'gallon' and lower(t.name) = 'fl oz';
insert into factors (factor_id, from_unit, to_unit, factor) select 56, f.unit_id, t.unit_id, 16 as factor from units f,units t where lower(f.name) = 'pint' and lower(t.name) = 'fl oz';
insert into factors (factor_id, from_unit, to_unit, factor) select 57, f.unit_id, t.unit_id, 8.0 as factor from units f,units t where lower(f.name) = 'cup (fluid)' and lower(t.name) = 'fl oz';
insert into factors (factor_id, from_unit, to_unit, factor) select 58, f.unit_id, t.unit_id, 33.8140227 as factor from units f,units t where lower(f.name) = 'liter' and lower(t.name) = 'fl oz';
insert into factors (factor_id, from_unit, to_unit, factor) select 59, f.unit_id, t.unit_id, 0.033814023 as factor from units f,units t where lower(f.name) = 'milliliter' and lower(t.name) = 'fl oz';
insert into factors (factor_id, from_unit, to_unit, factor) select 60, f.unit_id, t.unit_id, 0.33814203 as factor from units f,units t where lower(f.name) = 'centiliter' and lower(t.name) = 'fl oz';
insert into factors (factor_id, from_unit, to_unit, factor) select 61, f.unit_id, t.unit_id, 1000 as factor from units f,units t where lower(f.name) = 'kilogram' and lower(t.name) = 'gram';
insert into factors (factor_id, from_unit, to_unit, factor) select 62, f.unit_id, t.unit_id, 16 as factor from units f,units t where lower(f.name) = 'cup' and lower(t.name) = 'tablespoon';
insert into factors (factor_id, from_unit, to_unit, factor) select 63, f.unit_id, t.unit_id, 48 as factor from units f,units t where lower(f.name) = 'cup' and lower(t.name) = 'teaspoon';
insert into factors (factor_id, from_unit, to_unit, factor) select 64, f.unit_id, t.unit_id, 0.0625 as factor from units f,units t where lower(f.name) = 'cup (fluid) (UK)' and lower(t.name) = 'gallon (UK)';
insert into factors (factor_id, from_unit, to_unit, factor) select 65, f.unit_id, t.unit_id, 0.5 as factor from units f,units t where lower(f.name) = 'cup (fluid) (UK)' and lower(t.name) = 'pint (UK)';
insert into factors (factor_id, from_unit, to_unit, factor) select 66, f.unit_id, t.unit_id, 0.25 as factor from units f,units t where lower(f.name) = 'cup (fluid) (UK)' and lower(t.name) = 'quart (UK)';
insert into factors (factor_id, from_unit, to_unit, factor) select 67, f.unit_id, t.unit_id, 10.0 as factor from units f,units t where lower(f.name) = 'cup (fluid) (UK)' and lower(t.name) = 'fl oz (UK)';
insert into factors (factor_id, from_unit, to_unit, factor) select 68, f.unit_id, t.unit_id, 0.0002199692 as factor from units f,units t where lower(f.name) = 'milliliter' and lower(t.name) = 'gallon (UK)';
insert into factors (factor_id, from_unit, to_unit, factor) select 69, f.unit_id, t.unit_id, 0.001759754 as factor from units f,units t where lower(f.name) = 'milliliter' and lower(t.name) = 'pint (UK)';
insert into factors (factor_id, from_unit, to_unit, factor) select 70, f.unit_id, t.unit_id, 0.000879877 as factor from units f,units t where lower(f.name) = 'milliliter' and lower(t.name) = 'quart (UK)';
insert into factors (factor_id, from_unit, to_unit, factor) select 71, f.unit_id, t.unit_id, 0.0351950797 as factor from units f,units t where lower(f.name) = 'milliliter' and lower(t.name) = 'fl oz (UK)';
insert into factors (factor_id, from_unit, to_unit, factor) select 72, f.unit_id, t.unit_id, 1.0 as factor from units f,units t where lower(f.name) = '#2 can' and lower(t.name) = 'can';
insert into factors (factor_id, from_unit, to_unit, factor) select 73, f.unit_id, t.unit_id, 1.0 as factor from units f,units t where lower(f.name) = '14.5 oz can' and lower(t.name) = 'can';
insert into factors (factor_id, from_unit, to_unit, factor) select 74, f.unit_id, t.unit_id, 1.0 as factor from units f,units t where lower(f.name) = '#2.5 can' and lower(t.name) = 'large can';
insert into factors (factor_id, from_unit, to_unit, factor) select 75, f.unit_id, t.unit_id, 1.0 as factor from units f,units t where lower(f.name) = '#3 can' and lower(t.name) = 'large can';
insert into factors (factor_id, from_unit, to_unit, factor) select 76, f.unit_id, t.unit_id, 1.0 as factor from units f,units t where lower(f.name) = '29 oz can' and lower(t.name) = 'large can';


update food_conversions c
set unit_id = u.unit_id
from units u
where u.name = c.unit_name;