# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Init container image

on:
  workflow_dispatch:
    inputs:
      containerVersion:
        description: 'container version'
        required: true
        default: 'warning'

defaults:
  run:
    working-directory: listshop-service/src/main/docker/initStaticFiles

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/listshop-staticfiles:${containerVersion}
    - name: Logout of Docker
      run: docker logout
    - name: Log back in to Docker
      run: docker login --username=${{ secrets.DOCKER_HUB_USERNAME }} --password=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push to Dockerhub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/listshop-staticfiles:${containerVersion}